Improve the integration of the Metrics pipeline in the release
opentargets/ot-release-metrics-app pull request #19
Opened 2022-08-23 15:31 UTC by ireneisdoomed

This PR includes:
- The changes to adapt the metrics script to work with remote data ([#2613](https://github.com/opentargets/issues/issues/2613))
- The changes to parametrise the metrics script with a configuration file ([#2614](https://github.com/opentargets/issues/issues/2614))
- General repo restructure to make it cleaner

2022-09-08 15:55 UTC, DSuveges requested changes
I feel there's somethign off, we need to optimize probably the creation of the machine or the job submission.

2022-09-08 15:55 UTC, DSuveges commented on docs/metric-calculation.md
> +  --files='config/config.yaml'
Region is required to submit.

```suggestion
  --region=${CLUSTER_REGION} \
  --files='config/config.yaml'
```

2022-09-08 15:55 UTC, DSuveges commented on docs/metric-calculation.md
> +gcloud dataproc clusters create ${CLUSTER_NAME} \
This command create a cluster with a master and two workers. Is there a reason not to use a single node dataproc cluster?

2022-09-15 08:53 UTC, ireneisdoomed commented on docs/metric-calculation.md
> +gcloud dataproc clusters create ${CLUSTER_NAME} \
Thanks, I'd simply forgotten adding the flag.

2022-09-16 13:10 UTC, ireneisdoomed commented
I've been able to run the metrics script in ~20min for the first 22.09 pipeline run following the instructions in the README. Logs available at https://console.cloud.google.com/dataproc/jobs/ac69daf526dd4c6091b73e48e0fa2719/monitoring?region=europe-west1&project=open-targets-eu-dev

2022-09-16 13:10 UTC, merged